[build]
  command = "make build"
  functions = "netlify-functions"
  publish = "www/public"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/christopherbiscardi/christopherbiscardi.github.com"